package team23compiler;


import java.util.ArrayList;


//el class dh hwa el 3obara 3n node ay node fel shagra htb2 object mn el class dh w hyb2 leha parent w e5wat w children kman
class Treenode {
  
  private Treenode parent; //This variable represents the parent node of the current node. 
  Treenode sibling; //This variable represents the next sibling node of the current node.
  ArrayList <Treenode> children = new ArrayList(); //This ArrayList stores references to the child nodes of the current node.
  private static int nodeID = 0; //This static variable is used to generate unique identifiers for each node.
  private String nodeName = "Node "; //This variable holds the name of the node, which consists of the prefix "Node" followed by a unique identifier generated by nodeID
  String desc;   //this variable stores a description or label associated with the node.


  public Treenode(String d) { // dh el constructor w by5le el description bta3 ay node hwa d wel nodeName  bybzto bel ID wel ID byzed m3 kol node btt3ml 3shan lma tegy t3ml node gdeda yb2 3la id el zyada
      this.desc = d;
      this.nodeName = nodeName + nodeID + "" ;
      nodeID ++;
  }

  void addchild(Treenode x){  //This method adds a child node (x) to the list of children of the current node.
      children.add(x);
  }

  public void setSibling(Treenode sibling) { // This method sets the next sibling node of the current node.
      this.sibling = sibling;
  }

  public void setDesc(String desc) { //This method sets the description of the node.
      this.desc = desc;
  }

  public String getNodeName() { //This method returns the name of the node.
      return nodeName;
  }

  public String getDesc() { //This method returns the description of the node.
      return desc;
  }

}